# Generated by Django 5.0.6 on 2024-05-18 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='city',
            new_name='District',
        ),
        migrations.RenameField(
            model_name='building',
            old_name='state',
            new_name='Location',
        ),
        migrations.RenameField(
            model_name='building',
            old_name='zip_code',
            new_name='post_code',
        ),
    ]
