# Generated by Django 5.0.6 on 2024-05-18 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_rename_city_building_district_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='address',
        ),
    ]
