# Generated by Django 5.0.6 on 2024-05-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0004_flat_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='rent',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
    ]
